# Numpy

- Numberical python의 약자
- **수치 계산**을 하기 위해 만들어진 라이브러리
- 배열(array) 개념으로 변수를 사용하며 벡터, 행렬 등의 연산을 쉽고 빠르게 수행

In [3]:
import numpy as np

In [4]:
arr1  = np.arange(15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
# 차원을 확인하는 shape
arr1.shape

(3, 5)

In [6]:
# 데이터 타입을 확인하는 dtype
arr1.dtype

dtype('int64')

In [7]:
arr3 = np.zeros((3, 4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr2 = np.ones((3, 4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr4 = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype = np.float64)
arr4

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
arr5 = np.array([
    [7, 8, 9],
    [10, 11, 12]
], dtype = np.float64)

arr4 + arr5

array([[ 8., 10., 12.],
       [14., 16., 18.]])